Triple-T/gradle-play-publisher

- src/main/groovy/de/triplet/gradle/play/PlayPublisherPlugin.groovy
> documented the missing feature

- src/main/groovy/de/triplet/gradle/play/PlayPublisherPlugin.groovy
only debuggable app not accepted by google play store
> remove hardcoded buildType name filter

- README.md
As described in issue Triple-T/gradle-play-publisher#45, sometimes it's required to execute tasks from "play" plugin after executing custom task from user's gradle script.
We should add info how to achieve this goal to main `readme` page.
> Add section "Adding dependencies for "play" plugin tasks from user script"

- README.md
- src/main/groovy/de/triplet/gradle/play/LimitExceededException.groovy
- src/main/groovy/de/triplet/gradle/play/PlayPublishApkTask.groovy
- src/main/groovy/de/triplet/gradle/play/PlayPublishListingTask.groovy
- src/main/groovy/de/triplet/gradle/play/PlayPublisherPluginExtension.groovy
- src/main/groovy/de/triplet/gradle/play/TaskHelper.groovy
- src/test/groovy/de/triplet/gradle/play/TaskHelperTest.groovy
I implemented some logic to warn the user about the requirements of the play store. #64 
So now you will get an error if the texts exceeds the given limits.
For more look at the Updated README (7d2d02cd0dc2d099506f50476be375e0be396666).
> Error messages

- src/main/groovy/de/triplet/gradle/play/PlayPublisherPlugin.groovy
IntelliJ is a lot happier with this.
> Replaces array accessor [0] with .first()

- src/main/groovy/de/triplet/gradle/play/PlayPublishApkTask.groovy
- src/main/groovy/de/triplet/gradle/play/PlayPublishListingTask.groovy
- src/main/groovy/de/triplet/gradle/play/TaskHelper.groovy
- src/test/groovy/de/triplet/gradle/play/TaskHelperTest.groovy
> Merged checkForTextLength into readAndTrimFile

- README.md
- build.gradle
- src/main/groovy/de/triplet/gradle/play/PlayPublishApkTask.groovy
- src/main/groovy/de/triplet/gradle/play/PlayPublisherPluginExtension.groovy
- src/test/groovy/de/triplet/gradle/play/PlayPublisherPluginTest.groovy
> Support for staged rollouts

- README.md
As I was configuring the plugin, I found it helped me out to have a single checklist of all the things I needed to do. I thought it might be helpful to everyone else as well if I PR'd an update to the README. Thanks for making such a useful tool.
> updated read me to list all config requirements in a single location

- README.md
- src/main/groovy/de/triplet/gradle/play/AndroidPublisherHelper.groovy
- src/main/groovy/de/triplet/gradle/play/PlayPublishTask.groovy
- src/main/groovy/de/triplet/gradle/play/PlayPublisherPluginExtension.groovy
- src/test/groovy/de/triplet/gradle/play/PlayPublisherPluginTest.groovy
> JSON file credentials

- README.md
- src/main/groovy/de/triplet/gradle/play/BootstrapTask.groovy
- src/main/groovy/de/triplet/gradle/play/PlayPublishListingTask.groovy
Upload wear screenshots , #126
> add feature publish wear screenshots

- src/test/groovy/de/triplet/gradle/play/ImageFileFilterTest.groovy
In order to do an useful kata-like exercise, I created some tests for ImageFileFilter. Hope you find them  useful, too!
> Testing ImageFileFilter with some tests, to avoid breaking it in the future

- README.md
See #147 
The [source](https://github.com/Triple-T/gradle-play-publisher/blob/b85259e01869fd05fed83f87eb95e0c8246a2a8e/src/main/groovy/de/triplet/gradle/play/PlayPublishListingTask.groovy#L13) is fine.
> Fix typo of "size of title"

- src/main/groovy/de/triplet/gradle/play/PlayPublisherPlugin.groovy
- src/test/groovy/de/triplet/gradle/play/PlayPublisherPluginTest.groovy
#193 
Solved the dimension problem and should be working fine for dimensions, picking the first config found from the flavors in the variant as per how dimension-overriding should work. I have no idea how to actually use dimensions practically though so I'm unsure how to write a test that actually tests it.
> Fixed playaccountconfig for dimensions

- build.gradle
- src/main/resources/META-INF/gradle-plugins/com.github.triplet.play.properties
More informations: https://docs.gradle.org/current/userguide/javaGradle_plugin.html
> Use java-gradle-plugin

- src/main/groovy/de/triplet/gradle/play/PlayPublisherPlugin.groovy
… instead of `project.android`. This will increase IDE support as we now know the type.
> Use project.extensions.getByType(AppExtension.class)

- README.md
> explain how playAccountConfigs work

- src/main/groovy/de/triplet/gradle/play/PlayPublishListingTask.groovy
Update as per Google's current support documentation: https://support.google.com/googleplay/android-developer/answer/113469#details
Fixes #224
> Update title character limit to 50

- src/main/groovy/de/triplet/gradle/play/PlayPublisherPluginExtension.groovy
The Google Play Console supports a new Internal test track, see:
https://support.google.com/googleplay/android-developer/answer/3131213
This is available through the API by targeting the 'internal' track.
> Support for Google Play Console Internal test track.

- src/main/kotlin/de/triplet/gradle/play/AndroidPublisherHelper.kt
> Increase timeout to 100 seconds for connection and read

- plugin/src/main/kotlin/com/github/triplet/gradle/play/BootstrapTask.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PublishApkTask.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PublishListingTask.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Constants.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Inputs.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/PlayPublishPackageBase.kt
@bhurling or @ChristianBecker This should be merged normally since each commit addresses a different bug. (I was too lazy to make a gazillion PRs.)
> Fix bugs found in production

- README.md
> Add external tool usage instructions

- plugin/src/main/kotlin/com/github/triplet/gradle/play/BootstrapTask.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PublishListingTask.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Constants.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Listings.kt
They were never used together in the first place.
> Split AppDetail out of ListingDetail

- plugin/src/main/kotlin/com/github/triplet/gradle/play/BootstrapTask.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/GeneratePlayResourcesTask.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayAccountConfigExtension.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PublishApkTask.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PublishListingTask.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/AccountConfig.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/PlayPublishPackageBase.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/PlayPublishTaskBase.kt
- plugin/src/test/groovy/com/github/triplet/gradle/play/TestHelper.groovy
@bhurling This one should also be merged normally because it fixes a somewhat unrelated bug.
Fixes #267
> Add support for Gradle cache 

- README.md
> Remove references to invalid `uploadImages` flag

- plugin/src/test/groovy/com/github/triplet/gradle/play/PlayPublisherPluginTest.groovy
The removed test was Ignore'd for a while now. The test itself was unrelated to our plugin.
> Remove one Ignore'd test

- plugin/build.gradle.kts
Addresses first half of #306 so we no longer dump test dependencies into the published pom
> Exclude test dependencies from final pom

- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/PlayPublishPackageBase.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/GenerateResources.kt
> Fix crashes when play folders aren't available

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishBundle.kt
> Fix incorrect app bundle file name detection

- plugin/build.gradle.kts
> Oops! 😳 Re-enable Groovy tests

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
> Don't upload universal APK if splits are provided

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/Bootstrap.kt
> Fix possible NPE in bootstrapProducts

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/Bootstrap.kt
> Fix another minor bootstrap NPE

- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/Bootstrap.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/ProcessPackageMetadata.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishBundle.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishListing.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishProducts.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/ExtensionOptions.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/LifecycleHelperTask.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishPackageBase.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishTaskBase.kt
- plugin/src/test/groovy/com/github/triplet/gradle/play/PlayPublishTaskTest.groovy
> Reorganize internal tasks

- CHANGELOG.md
This assumes #322, #389, #375 are going to be merged.
> Finalize release notes

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/Bootstrap.kt
> Finally bootstrap high res graphics

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishListing.kt
> Short circuit image uploads if remote and local contents of graphics for type are identical

- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Plugins.kt
- plugin/src/test/kotlin/com/github/triplet/gradle/play/CompatibilityTest.kt
> Fix compatibility issues on old Gradle versions that don't know how to unwrap Providers

- README.md
> Add both Kotlin and Groovy DSL samples to docs

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/GenerateResources.kt
This is another issue related to #451
> Fix broken language merges in Gradle 5

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/ProcessPackageMetadata.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PromoteRelease.kt
* Replace `map().flatten()` with `flatMap()`
* Replace `?: emptyList()` with `orEmpty()`
> Make better use of the Kotlin stdlib

- README.md
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/ExtensionDefaults.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Tracks.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Validation.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/ExtensionOptions.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishPackageBase.kt
- plugin/src/test/groovy/com/github/triplet/gradle/play/PlayPublisherPluginTest.groovy
> Remove rollout track and merge releases when using inProgress

- README.md
We're no longer on maven central
> Link to plugin portal in version badge

- README.md
> Update Groovy sample in README to compile

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishTaskBase.kt
following comment https://github.com/Triple-T/gradle-play-publisher/pull/478#issuecomment-447221229
> Increase network timeout to 5 mins

- README.md
> Add missing Internal track

- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/ExtensionDefaults.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Tracks.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Validation.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PromoteRelease.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/ExtensionOptions.kt
- plugin/src/test/groovy/com/github/triplet/gradle/play/PlayPublishTaskTest.groovy
- plugin/src/test/groovy/com/github/triplet/gradle/play/PlayPublisherPluginTest.groovy
> Remove track validation to support custom tracks

- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
> Check for custom signed outputs

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/Bootstrap.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishTaskBase.kt
The worker API is actually available as far back as 3.1.
> Parallelize bootstrap image downloads

- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
See https://github.com/Triple-T/gradle-play-publisher/issues/498#issuecomment-455262540
> Log error if a potential release build is debuggable

- plugin/build.gradle.kts
> Fix snapshot deployment

- README.md
> Add one-time promotion instructions

- README.md
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Validation.kt
> Allow disabling GPP

- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishBundle.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/ExtensionOptions.kt
> Support providing prebuilt artifacts instead of forcing a build on-the-fly

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/GenerateResources.kt
- plugin/src/test/groovy/com/github/triplet/gradle/play/GenerateResourcesTest.groovy
> Only merge graphics across categories

- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Validation.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishTaskBase.kt
- plugin/src/test/groovy/com/github/triplet/gradle/play/PlayPublisherPluginTest.groovy
Fixes #552, fixes #549, fixes #548
> Fix numerous credential validation inconsistencies and merge bugs

- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
> Fix bug causing app to be built even with artifact dir specified

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishPackageBase.kt
> Support specifying mapping files to upload with custom artifact dir

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/GenerateResources.kt
> Fix default language merge bugs

- plugin/build.gradle.kts
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PromoteRelease.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingApk.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingBundle.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishListing.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/CliOptions.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/LifecycleTasks.kt
> Support uploading internal sharing artifacts

- plugin/build.gradle.kts
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/ProcessArtifactMetadata.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PromoteRelease.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishBundle.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingBundle.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishArtifactBase.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayWorkers.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PublishBundleBase.kt
- plugin/src/test/groovy/com/github/triplet/gradle/play/TestHelper.groovy
- plugin/src/test/kotlin/com/github/triplet/gradle/play/CompatibilityTest.kt
- plugin/src/test/kotlin/com/github/triplet/gradle/play/Helpers.kt
> Fix bundle support

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingApk.kt
> Always upload universal APK

- README.md
Fixes #603
- Added descriptions to `README.md` about
- `userFraction` usage
- Default values of configurations
> Clarify track configuration default values

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishBundle.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingBundle.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/Agp.kt
> Fix yet another never-ending compatibility issue with AGP bundles

- README.md
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Constants.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Io.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Plugins.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/Bootstrap.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/CommitEdit.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/GenerateEdit.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/ProcessArtifactMetadata.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PromoteRelease.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishBundle.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingApk.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingBundle.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishListing.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishProducts.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/EditTaskBase.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishArtifactBase.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishEditTaskBase.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishTaskBase.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishingApi.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayWorkers.kt
> Transition to an atomic edit commit model

- gradle/wrapper/gradle-wrapper.properties
- plugin/build.gradle.kts
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Validation.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/Agp.kt
- plugin/src/test/groovy/com/github/triplet/gradle/play/TestHelper.groovy
- plugin/src/test/kotlin/com/github/triplet/gradle/play/CompatibilityTest.kt
- plugin/src/test/kotlin/com/github/triplet/gradle/play/Helpers.kt
> Update deps (includes bundle fix)

- README.md
> Add extensive docs on combining releases

- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/ExtensionDefaults.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PromoteRelease.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/CliOptions.kt
> Support publishing and promote artifacts within a single build

- plugin/build.gradle.kts
- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/ExtensionDefaults.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishBundle.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayWorkers.kt
- plugin/src/test/kotlin/com/github/triplet/gradle/play/PlayPublisherExtensionTest.kt
> Support retaining various app objects

- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/ExtensionDefaults.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/ExtensionModels.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayWorkers.kt
> Fix rollout publishing bugs

- README.md
> Improve service account setup guide

- plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/Bootstrap.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/CommitEdit.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/GenerateEdit.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/GenerateResources.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PromoteRelease.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishBundle.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingApk.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingBundle.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishListing.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishProducts.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayWorkers.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PublishArtifactTaskBase.kt
> Migrate to new Gradle Worker API

- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/Bootstrap.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishProducts.kt
> Bug fixes and improvements around in-app products

- plugin/build.gradle.kts
- plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Validation.kt
- plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/Agp.kt
- plugin/src/test/groovy/com/github/triplet/gradle/play/TestHelper.groovy
- plugin/src/test/kotlin/com/github/triplet/gradle/play/CompatibilityTest.kt
- plugin/src/test/kotlin/com/github/triplet/gradle/play/Helpers.kt
> Bump deps to fix AGP 3.6 alpha 11 incompatibility

- README.md
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Validation.kt
> Deprecate PKCS12 based auth

- .circleci/config.yml
- play/plugin/build.gradle.kts
- settings.gradle.kts
- testapp/build.gradle.kts
> Fix snapshot builds and test app bootstrapping issues

- README.md
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/InstallInternalSharingArtifact.kt
- play/plugin/src/test/fixtures/InstallInternalSharingArtifactIntegrationTest/src/main/AndroidManifest.xml
- play/plugin/src/test/fixtures/InstallInternalSharingArtifactIntegrationTest/src/main/java/com/example/publisher/MainActivity.java
- play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/InstallInternalSharingArtifactIntegrationTest.kt
- testapp-setup.gradle.kts
- testapp/build.gradle.kts
> Support installing Internal Sharing artifacts

- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PromoteRelease.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishBundle.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/workers/ArtifactWorkerBase.kt
- play/plugin/src/test/fixtures/PromoteReleaseIntegrationTest/src/consoleNames/play/release-names/custom-track.txt
- play/plugin/src/test/fixtures/PromoteReleaseIntegrationTest/src/consoleNames/play/release-names/default.txt
- play/plugin/src/test/fixtures/PromoteReleaseIntegrationTest/src/consoleNames/play/release-names/promote-track.txt
- play/plugin/src/test/fixtures/PromoteReleaseIntegrationTest/src/releaseNotes/play/release-notes/en-US/default.txt
- play/plugin/src/test/fixtures/PromoteReleaseIntegrationTest/src/releaseNotes/play/release-notes/en-US/promote-track.txt
- play/plugin/src/test/fixtures/PublishApkIntegrationTest/src/consoleNames/play/release-names/custom-track.txt
- play/plugin/src/test/fixtures/PublishApkIntegrationTest/src/consoleNames/play/release-names/default.txt
- play/plugin/src/test/fixtures/PublishApkIntegrationTest/src/releaseNotes/play/release-notes/en-US/default.txt
- play/plugin/src/test/fixtures/PublishBundleIntegrationTest/src/consoleNames/play/release-names/custom-track.txt
- play/plugin/src/test/fixtures/PublishBundleIntegrationTest/src/consoleNames/play/release-names/default.txt
- play/plugin/src/test/fixtures/PublishBundleIntegrationTest/src/releaseNotes/play/release-notes/en-US/default.txt
- play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/PromoteReleaseIntegrationTest.kt
- play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/PublishApkIntegrationTest.kt
- play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/PublishBundleIntegrationTest.kt
- testapp/src/main/play/release-notes/en-US/alpha.txt
> Fix bug where specifying promoteTrack used incorrect release notes and name

- common/utils/src/main/kotlin/com/github/triplet/gradle/common/utils/Io.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Plugins.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/GenerateResources.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishListing.kt
- play/plugin/src/test/fixtures/GenerateResourcesIntegrationTest/src/staging/play/listings/ja-JA/parent-child-test.txt
- play/plugin/src/test/kotlin/com/github/triplet/gradle/play/helpers/IntegrationTestBase.kt
- play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/GenerateResourcesIntegrationTest.kt
> Rewrite Play resource generator

- README.md
> Improve setup guide

- common/validation/src/main/kotlin/com/github/triplet/gradle/common/validation/RuntimeValidationPlugin.kt
- common/validation/src/main/kotlin/com/github/triplet/gradle/common/validation/RuntimeValidator.kt
- common/validation/src/main/kotlin/com/github/triplet/gradle/common/validation/Validation.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- testapp/build.gradle.kts
> Clarify errors when AGP isn't available

- buildSrc/src/main/kotlin/Config.kt
- play/android-publisher/build.gradle.kts
- play/android-publisher/src/main/kotlin/com/github/triplet/gradle/androidpublisher/internal/AndroidPublisher.kt
Pull Request for the issue #826
> Add proxy authentication

- README.md
> Change updatePriority to Int in README

- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Extensions.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Plugins.kt
- play/plugin/src/test/kotlin/com/github/triplet/gradle/play/PlayPublisherExtensionTest.kt
- play/plugin/src/test/kotlin/com/github/triplet/gradle/play/PlayPublisherPluginIntegrationTest.kt
> Fix shared global extension object

- .github/ISSUE_TEMPLATE/1-bug.md
I made a minor enchacement so as a Windows user can retrieve the required version info in the Windows terminal.
The command verified in a Windows 10 machine via Android Studio Terminal.
> Enchance bug template

- README.md
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingApk.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingBundle.kt
- play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/shared/PublishInternalSharingArtifactIntegrationTests.kt
Hi, I created a PR to fix #928
> Use the apk/aab file name for internal sharing json file names

- README.md
Adds docs example to increase the rollout of existing in-progress release using `update` flag!
> Update README.md (adds example of how to use `update` flag)

- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
> Fix crash resolving dependencies on Gradle 6.9

- play/android-publisher/src/main/kotlin/com/github/triplet/gradle/androidpublisher/PublisherModels.kt
- play/android-publisher/src/main/kotlin/com/github/triplet/gradle/androidpublisher/internal/DefaultEditManager.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/ProcessArtifactVersionCodes.kt
- play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/ProcessArtifactVersionCodesIntegrationTest.kt
fixes https://github.com/Triple-T/gradle-play-publisher/issues/1077
> Restore 3.7 auto behavior (fixes #1077)

- play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
> Remove indirect usage of now deprecated conventions
