Triple-T/gradle-play-publisher

.travis.yml
src/main/groovy/de/triplet/gradle/play/BootstrapTask.groovy
src/main/groovy/de/triplet/gradle/play/PlayPublishApkTask.groovy
src/main/groovy/de/triplet/gradle/play/PlayPublishListingTask.groovy
src/main/groovy/de/triplet/gradle/play/PlayPublishTask.groovy
src/main/groovy/de/triplet/gradle/play/PlayPublisherPlugin.groovy
src/test/groovy/de/triplet/gradle/play/PlayPublishTaskTest.groovy
src/test/groovy/de/triplet/gradle/play/TestHelper.groovy

This should resolve #54 
This removes the `applicationId` field entirely from `PlayPublishTask` and instead keeps a `variant` field. This way, the applicationId retrieval can wait until the task actually runs, allowing for any user change to the applicationId during project configuration without causing the upload to fail later due to an out-of-date applicationId.
I've added a test as well. Please let me know if I should change/improve/fix it in anyway, as I haven't written a test for groovy before.

Defer applicationId retrieval to when the publish task runs

---

build.gradle

Unfortunately I was unable to find a changelog or release notes, so it's up to you if this gets merged in.

Updated AndroidPublisher dependency from rev16-1.19.1 to rev18-1.20.0

---

src/main/groovy/de/triplet/gradle/play/PlayPublisherPlugin.groovy
src/test/groovy/de/triplet/gradle/play/PlayPublisherPluginTest.groovy
src/test/groovy/de/triplet/gradle/play/TestHelper.groovy

see #100 
~~I assumed if there are no signingConfig, throw `IllegalArgumentException`. If you don't want to create the publishApk task names, let me know. I will put the validation back to `PlayPublisherPlugin`.~~

Made signingConfig not require for bootstrapping and lisitng tasks

---

README.md

Following the readme, I've seen that the default userFraction was 0.1. I thought it was a porcentage, like in the Google Play environment. But 1 meant 100%, not 1%... so I propose to add this small clarification, to avoid doing the mistake of publishing a version at 50% instead of 0.5%, as I did :·)

Adding a clarification of the userFraction param in the README.md

---

src/main/groovy/de/triplet/gradle/play/TaskHelper.groovy
src/test/groovy/de/triplet/gradle/play/TaskHelperTest.groovy

Special characters like umlauts are counted as more than one character while Google counts them as only one. Use BreakIterator for better counting.

Fix character counting

---

src/main/groovy/de/triplet/gradle/play/PlayPublishTask.groovy
src/test/groovy/de/triplet/gradle/play/PlayPublishTaskTest.groovy

- Noticed that when I run a `publishListing`, it was not updating the `fil` locale with screenshots.
- Fixed the matcher regex to include the `fil` locale.
- I am not an expert in regex, but this seems to work.
- Added a couple of tests to verify

Fix regex for Filipino locale for publishing

---

README.md
src/main/groovy/de/triplet/gradle/play/PlayPublisherPlugin.groovy
src/main/groovy/de/triplet/gradle/play/PlayPublisherPluginExtension.groovy
src/main/groovy/de/triplet/gradle/play/PlayUntrackTask.groovy
src/test/groovy/de/triplet/gradle/play/PlayPublisherPluginTest.groovy
src/test/groovy/de/triplet/gradle/play/PlayUntrackTaskTest.groovy

This commit adds untrackApk task for the plugin to allow user to untrack
app from another Play Store channel when they are using 2 different
channels to deploy their app.
```
gradle untrackApkRelease
```
This commit adds `untrack` and `untrackFormat` properties to the
extension to allow further customisation on which version of the app to
be disabled from Play Store.
```groovy
play {
// untrack from alpha any active versions between 300 and 399
untrack = 'alpha'
untrackFormat = '^3[0-9]{2}\$'
}
```

Add Untrack APK task

---

build.gradle

Hi @ChristianBecker !
Today we started facing issues with the `publishRelease` task on our gradle tasks.
```
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal Server Error
{
"code" : 500,
"message" : null
}
at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
at …
```

Update google publisher library

---

gradle.properties
src/main/groovy/de/triplet/gradle/play/PlayPublishApkTask.groovy

Code should omit exception thrown when there is no active version in track.
`Execution failed for task ':App:publishApkAgentRelease'.
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
>   {
>     "code" : 404,
>     "errors" : [ {
>       "domain" : "androidpublisher",
>       "message" : "Track not found: no APK version codes in the specified track.",
>       "reason" : "trackEmpty"
>     } ],
>     "message" : "Track not found: no APK version codes in the specified track."
>   }
> `

Untracking throws exception

---

src/main/groovy/de/triplet/gradle/play/PlayPublisherPlugin.groovy
src/test/groovy/de/triplet/gradle/play/DependsOn.groovy
src/test/groovy/de/triplet/gradle/play/PlayPublisherPluginTest.groovy

We don't need to depend on all the specific assemble tasks for each output. `assemble{Variant}Release` already collects all these tasks for us.

let apk task depend on general assemble task - #189

---

src/main/groovy/de/triplet/gradle/play/PlayPublishApkTask.groovy
src/main/groovy/de/triplet/gradle/play/PlayPublishListingTask.groovy
src/main/groovy/de/triplet/gradle/play/PlayPublisherPlugin.groovy
src/main/groovy/de/triplet/gradle/play/TaskHelper.groovy
src/test/groovy/de/triplet/gradle/play/TaskHelperTest.groovy

Include the complete relative path of the file that exceeds its limit in the IllegalArgumentException. Fixes #172
FYI @bhurling

More descriptive message when text exceeds length

---

build.gradle
gradle.properties
src/test/groovy/de/triplet/gradle/play/TestHelper.groovy

This change ensures backwards compatibility in case people are still using a version of Gradle lower than 4.4 (See comment https://github.com/Triple-T/gradle-play-publisher/issues/259#issuecomment-390972786). You can find a list of compatible versions at https://developer.android.com/studio/releases/gradle-plugin#behavior_changes_2.
With that change we can now safely release a version 1.2.1. Bumping the android plugin version should be considered a breaking change.
cc @ChristianBecker

Downgrade android plugin to 2.3.0 to not break other people's builds

---

build.gradle

Even if we don't migrate yet to the v3, we should at least use the latest V2 available.

Update to latest androidpublisher v2

---

src/main/kotlin/de/triplet/gradle/play/Constants.kt
src/main/kotlin/de/triplet/gradle/play/Extensions.kt
src/main/kotlin/de/triplet/gradle/play/PlayPublisherPlugin.kt
src/test/groovy/de/triplet/gradle/play/PlayPublisherPluginTest.groovy

Adds "All" level tasks for each of the tasks currently supported. Used #249 as the basis.
#117 is covered in this
This will also lays the groundwork for any other "all tasks", such as:
- Promoting builds to different channels
- Adding/updating in-app products #181

All flavors

---

src/main/kotlin/de/triplet/gradle/play/AndroidPublisherHelper.kt
src/main/kotlin/de/triplet/gradle/play/CredentialProvider.kt
src/main/kotlin/de/triplet/gradle/play/PlayAccountConfig.kt
src/main/kotlin/de/triplet/gradle/play/PlayPublisherPluginExtension.kt

This makes the code easier to read, and means that we can better manage the process if it were to change (ie: Deprecating the old pk12 Files in the future, hopefully!)

Abstract the credential stuff into a provider class.

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/Config.kt
plugin/build.gradle.kts

This way we only have to declare the Kotlin version once, so I got rid of the `buildSrc` for now.

Simplify Kotlin dependencies by using a KotlinDependencyExtension

---

build.gradle.kts

This [Gradle plugin](https://github.com/ben-manes/gradle-versions-plugin) creates a new task `gradle dependencyUpdates` (or short `gradle dU`) that will display outdated dependencies.
For our current setup this will look like
```
> Task :dependencyUpdates
------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------
The following dependencies are using the latest milestone version:
- org.assertj:assertj-core:3.10.0
- com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.17.0
- junit:junit:4.12
- org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.2.41
- org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.41
- …
```

Add Versions plugin

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Plugins.kt
plugin/src/test/groovy/com/github/triplet/gradle/play/PlayPublisherPluginTest.groovy

This one is up for debate: the generate tasks are internal and don't really serve a purpose outside of prepping for the publish listing task so I don't see why we should add another user facing task. What do you guys think?

Remove generateAll task

---

.buildscript/deploy_snapshot.sh
.travis.yml
README.md
gradle.properties
plugin/gradle.properties

See the [latest SNAPSHOT releases](https://oss.sonatype.org/content/repositories/snapshots/com/github/triplet/gradle/play-publisher/2.0.0-SNAPSHOT/). The last one (`play-publisher-2.0.0-20180605.085714-2.jar`) was created from a preview version of this commit.

Auto-deploy snapshots from Travis CI to Sonatype

---

plugin/build.gradle.kts

Unfortunately, there are no release notes available. But the build is green, so we're good to go!

Update AndroidPublisher to v3-rev12-1.23.0

---

CHANGELOG.md

Can go into master as the changelog states that 2.0.0 has not been released yet

Start adding v2.0 release notes

---

CHANGELOG.md

The release names were really small and made the structure hard to understand.

Improve changelog structure

---

CHANGELOG.md
plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/ExtensionOptions.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Io.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/PlayPublishPackageBase.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishListing.kt
plugin/src/test/kotlin/com/github/triplet/gradle/play/ExtensionsTest.kt

I haven't touched this "feature" because I thought it was a user request (otherwise why would there by an extra config option), but it turns out this was just another case of trying to Do the Right Thing™️.
Feature origin story:
- Originally, file lengths weren't checked when uploaded
- Checks were added, but they trimmed the files by default
- #66 fixed that bug with a config flag instead of just throwing on overflow
I don't see any possible case where someone would want non-deterministic behavior so this feature should be killed, hence the PR.

Remove nonsensical trim feature

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
plugin/src/test/groovy/com/github/triplet/gradle/play/PlayPublisherPluginTest.groovy

This follows the convention established by the AGP. For example, there `assembleDebug` and `assembleRelease`. The combination of the two is simply `assemble`, not `assembleAll`.
PS: this isn't a breaking change because these tasks were introduced in v2.0.

Remove `All` suffix from tasks

---

CHANGELOG.md
plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
plugin/src/test/groovy/com/github/triplet/gradle/play/PlayPublishTaskTest.groovy
plugin/src/test/groovy/com/github/triplet/gradle/play/PlayPublisherPluginTest.groovy

Example Android tasks:
- transformClassesWithDexBuilder**For**Release
- assemble**Release**
- generate**Release**Sources
The AGP never puts the variant at the end of the task name unless it's prefixed with `for` or it's the last word. Migrate our tasks to this: `publishApkRelease` -> `publishReleaseApk`. It sounds a lot nicer IMO.

Follow variant task naming conventions

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Constants.kt
plugin/src/test/groovy/com/github/triplet/gradle/play/GenerateResourcesTest.groovy

In my quest to improve the plugin UX, I noticed that we were dumping our generated files into `outputs` which is meant to be a user facing directory. This PR moves our generated files to a more appropriate `generated/gpp` directory.

Remove gen files from user friendly output dir

---

CHANGELOG.md
plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayAccountConfigExtension.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/AccountConfig.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/PlayPublishTaskBase.kt
plugin/src/test/groovy/com/github/triplet/gradle/play/PlayPublisherPluginTest.groovy
plugin/src/test/groovy/com/github/triplet/gradle/play/TestHelper.groovy

Motivation: `pk12File` and `jsonFile` are meaningless names and make for a pretty unpleasant API. The new API unifies those files under the banner of `serviceAccountCredentials` and intelligently selects the right credential while providing descriptive errors messages if something doesn't match up.

Simplify Service Account credentials API

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayAccountConfigExtension.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/AccountConfig.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Io.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/PlayPublishPackageBase.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/GenerateResources.kt

- Make release notes dir optional (aka don't crash if it isn't there)
- Remove pointless network call updating tracks
- Update out-of-date credentials annotations
Closes #358

Release notes fixes and other annotation improvements

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/LifecycleHelperTask.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Plugins.kt

Supports `./gradlew publish --foo=bar` and the other lifecycle tasks.

Support global CLI options

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Plugins.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Validation.kt
plugin/src/test/kotlin/com/github/triplet/gradle/play/CompatibilityTest.kt

Since we're no longer bundling the AGP, there's no way for us to make sure at least the minimum supported AGP and Gradle versions are being used. This PR adds runtime validation.

Validate runtime

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/PlayPublishPackageBase.kt

Turns out `lazy` was screwing us over because Gradle checks the property multiple times.

Fix crash if no release notes are provided

---

plugin/build.gradle.kts
plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
plugin/src/test/kotlin/com/github/triplet/gradle/play/CompatibilityTest.kt

We have the `CompatibilityTest` to make sure things work on older versions.

Fix deprecations with AGP 3.3

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/ProcessPackageMetadata.kt
plugin/src/test/groovy/com/github/triplet/gradle/play/PlayPublisherPluginTest.groovy

Allow signed variants to be built without creds when resolution strategy is not auto

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Plugins.kt

Circumvent task name conflicts by prefixing names with "gpp" should one occur

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Validation.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/ProcessPackageMetadata.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishBundle.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishListing.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishPackageBase.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishTaskBase.kt

Fixes #441
When using `ResolutionStrategy.AUTO` there still might be flavors that are not supposed to be published. Processing the package metadata would fail the build. However, we don't know that a flavor isn't published until we've tried

Ignore application not found errors during metadata processing

---

.buildscript/deploy_snapshot.sh
README.md
build.gradle.kts
gradle.properties
plugin/build.gradle.kts
plugin/gradle.properties
plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
plugin/src/test/groovy/com/github/triplet/gradle/play/PlayPublisherPluginTest.groovy
settings.gradle.kts

#154
Publishing to Gradle Plugin Portal:
`./gradlew publishPlugins -Pgradle.publish.key=<key> -Pgradle.publish.secret=<secret>`
Complete guide [here](https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/).
Publishing to mavenLocal:
`./gradlew publishToMavenLocal`
Using from mavenLocal:
```gradle
// settings.gradle:
pluginManagement {
repositories {
gradlePluginPortal()
mavenLocal()
}
}
// build.gradle:
plugins {
id "com.android.application"
id "com.github.triplet.play" version "2.0.0-SNAPSHOT" // Snapshots require Gradle 4.10+
}
```
POM is the same as before.
Javadoc jar is no longer published because it was empty.
Publishing snapshots to Sonatype should theoretically work if `SONATYPE_NEXUS_USERNAME` and `SONATYPE_NEXUS_PASSWORD` are provided but I can't test it right …

Publish to Gradle Plugin Portal

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PromoteRelease.kt

Our current validation fails the task if we receive unexpected responses from the publisher API. Instead, we should filter out these responses so that only valid tracks are selected or the task fails softly with a warning where there are no valid tracks.

Move promote validation before track selection

---

README.md

Right now, the README.md introduces "in progress" and "inProgress", and the reader has to wonder about which one is the correct one. Let's talk just about `inProgress`, to avoid confusion.

Reduce confusion around "inProgress" naming in README

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishBundle.kt

Fixes #516
Googler's response:
> Unfortunately there is no way to get that using the variant API. Other than hardcoding the bundle path, there is one (slightly hacky) option: ...
Basically, there's no stable way to get the bundle path. I've checked and this API works all the way back to 3.2 when AGP added bundles so I think we're good. We'll just have to fix things again when they break.

Fix broken app bundle uploading

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/ProcessPackageMetadata.kt

Always run `outputProcessor` if resolution strategy is set to auto

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PublishingApi.kt

Over time, we've been continuously increasing the timeout without much success (people still run into timeout exceptions). The main problem is that the Publisher API makes us wait for it to do all sorts of processing and validation synchronously. This means we're at the mercy of however long it takes the API to do its thing. Given all the uncertainty, this PR makes the timeout indefinite. Worst case scenario, devs will just have to manually kill a stalled build.

Permanently fix timeout issues

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt

Make BuildConfig generation wait on output processors

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PromoteRelease.kt

We now just pick the highest version code which should be guaranteed to always work.

Fix bug auto selecting least stable track to promote release

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingApk.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/Agp.kt

It's super easy to make a mistake when tabbing to find a file. Usually, you have to delete the file name to get back to the directory that GPP will understand. This is annoying, so GPP should be lenient and accept those files if they seem correct.

Make artifactDir property accept files

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/ExtensionDefaults.kt
plugin/src/test/kotlin/com/github/triplet/gradle/play/PlayPublisherExtensionTest.kt

Notably, only the base and variant extensions were merged. This meant extensions didn't cascade properly if a user had a combination of variant, flavor, and build type overrides.

Fix extension merging bugs

---

.travis.yml

Re-created the two environment variables `SONATYPE_NEXUS_USERNAM`E and `SONATYPE_NEXUS_PASSWORD` using the [travis gem](https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables).

Update encrypted environment variables for TravisCI integration

---

plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingApk.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishListing.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/Agp.kt
plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/CliOptions.kt

Fixes #671
Also:
- Allows multiple APKs to be uploaded to internal sharing in the same build.
- Fixes inconsistencies with `--artifact-dir` by always using the rootProject as the relative path

Bug fixes and improvements around custom internal sharing artifacts

---

common/validation/src/main/kotlin/com/github/triplet/gradle/common/validation/RuntimeValidator.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Validation.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/GenerateEdit.kt

Because of line break it's handled like an invalid url
Now the url should be in a new line and be clickable

Rework line breaks in output messages to be more console friendly

---

build.gradle.kts
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/UploadArtifactTaskBase.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/PublishBundleIntegrationTest.kt

Fixes a failure when invoking `publishMyVariantBundle` with `-x bundleMyVariant`.
Fixes #784.

Allow non-existent mapping files

---

gradle/wrapper/gradle-wrapper.properties
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Validation.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/PlayPublisherPluginIntegrationTest.kt

Fixes #797
Gradle 6.3 contains this PR https://github.com/gradle/gradle/pull/12265
It requires deprecation messages to specify when they will go away using a new API
Please note that I have not searched through the entire project here to see if DeprecationLogger is used in other places. It may be. This is the one from the stack my project through
[Edited: the PR was changed based on feedback to use the regular logger, so will be backwards- + forwards-compatible with gradle versions now]
Hopefully it's useful!

Forward-port DeprecationLogger usage to Gradle 6.3

---

play/android-publisher/src/main/kotlin/com/github/triplet/gradle/androidpublisher/EditManager.kt
play/android-publisher/src/main/kotlin/com/github/triplet/gradle/androidpublisher/internal/DefaultEditManager.kt
play/android-publisher/src/test/kotlin/com/github/triplet/gradle/androidpublisher/internal/DefaultEditManagerTest.kt
play/android-publisher/src/testFixtures/kotlin/com/github/triplet/gradle/androidpublisher/FakeEditManager.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishBundle.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingBundle.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/PublishApkIntegrationTest.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/PublishBundleIntegrationTest.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingApkIntegrationTest.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingBundleIntegrationTest.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/shared/ArtifactIntegrationTests.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/shared/PublishArtifactIntegrationTests.kt

This PR updates `publishBundle` and `uploadPrivateBundle` tasks. When `artifactsDir` is specified, both tasks will now upload all bundle files found in the artifacts directory.
✅ Tests pass
✅ Checked with real project 
✅ Documentation verified (no update needed)
Closes: https://github.com/Triple-T/gradle-play-publisher/issues/914

Upload all bundle files in the artifacts directory

---

play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Plugins.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/CommitEdit.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishBundle.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayApiService.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/helpers/IntegrationTest.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/helpers/IntegrationTestBase.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/CommitEditIntegrationTest.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/GenerateEditIntegrationTest.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/shared/PublishArtifactIntegrationTests.kt

Follow up PR of https://github.com/Triple-T/gradle-play-publisher/pull/1084 partially addressing #1083 
In order to work con `Gradle 8.1.1` Configuration Cache issues, we need to bump Gradle, AGP to `8.0.0` and set the minimum JDK to 11 (17 for running the tests).
All these changes were done in the first commit. 
Focussing exclusively on `CommitEdit` task, I've made some changes as @ZacSweers suggested but still I didn't manage to get it to work as `onlyIf` seems to be computed at configuration time ([asked in Slack if this is expected, probably will fill an issue](https://gradle-community.slack.com/archives/C013WEPGQF9/p1682304058131779))
Said that, there are still many tests broken if we enable CC for the whole test suite, so being fully compatible with CC is going to be a more complex …

Fixes `CommitEdit` issues when enabling ConfigurationCache

---

settings.gradle.kts

Fixes https://github.com/Triple-T/gradle-play-publisher/issues/1074
I wanted to updated only the Google API Client, but the original issue was with the `android-publisher` being incompatible with Google API client 2.x.
I was not able to find a changelog for `android-publisher`. I just realized that last release was 2.0 by looking at the source: https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-androidpublisher/v3
Not sure how you handle these kinds of updates.
Google API client has an updated changelog instead: https://github.com/googleapis/google-api-java-client/releases.
I was able to integrate it in an existing project and it seems to work. Also, all unit tests pass.

Update play google-api-client 2.2.0 and android-publisher to 2.0.0

---

play/android-publisher/src/main/kotlin/com/github/triplet/gradle/androidpublisher/internal/DefaultEditManager.kt

Fix #1109 
Recognise the "Version code" prefix by making the comparison case insensitive.

#1109 Fix build fails on the version conflict with ResolutionStrategy.IGNORE

---

README.md

The Google Play Developer API no longer requires linking a developer play console account to a google cloud project.
Source: https://developers.google.com/android-publisher/getting_started
So, this PR updates setup instructions to avoid confusion.

Update creating service account instructions

---

play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/workers/PublishArtifactWorkerBase.kt

Gradle has an [issue](https://github.com/gradle/gradle/issues/862) that `DirectoryProperties.file()` does always resolve file names with colon (`:`) as URI. This breaks when a colon is used as part of a file name.
In this case this is needed for the dedicated PlayStore tracks: tv and wear. They require a corresponding prefix separated by a colon, e.g. "tv:internal". See: developers.google.com/android-publisher/tracks#ff-track-name
Resolving the file paths without `DirectoryProperty.file` does work around this Gradle issue on Plugin side.
Hey there! So you want to contribute to Gradle Play Publisher?
Before you file this pull request, follow these steps:
- Read [the contribution guidelines](https://github.com/Triple-T/gradle-play-publisher/blob/master/CONTRIBUTING.md).
- If this has been …

Workaround for colon track names

---

build.gradle.kts

I just came across the old usage of defining output.
I changed it.
Honestly, I'm not sure if it works 😅 
But I also have never seen such an setup anyways.. So 🤷 
More info about the deprecation:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Use new github action output command

---

.github/workflows/cid.yml
build.gradle.kts

Better solution than #1123 🙃 
This time I also tested it on my fork.
See a non-snapshot version run:
https://github.com/StefMa/gradle-play-publisher/actions/runs/8371003805
vs a snapshot version run:
https://github.com/StefMa/gradle-play-publisher/actions/runs/8371010999
This one fails because I can't publish snapshots on the fork.
However, the idea is that the job `deploy_snapshot` runs; and this is what it does.

Use new github actions output syntax

---

play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/PlayPublisherPluginIntegrationTest.kt

Fixes https://github.com/Triple-T/gradle-play-publisher/issues/1128
If present, sets up the sentry proguard mapping upload task (https://github.com/getsentry/sentry-android-gradle-plugin/blob/f9b82ddce3af1a21eec54da8b1c02e36c063939a/plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingsTask.kt#L114C13-L117C24) as a task dependency.

Run sentry crash reporting plugin on publish

---

play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/workers/PublishArtifactWorkerBase.kt

Handle release track names containing a colon (e.g. wear:alpha) gracefully without crashing.
https://github.com/Triple-T/gradle-play-publisher/issues/1088
For releases named `formfactor:track`, try `formfactor-track.txt` and `track.txt` instead of invalid filename `formfactor:track.txt`
https://github.com/chimbori/gradle-play-publisher/commit/cb5729afa399e1980231af67cf6670647d479915

Handle release track names containing a colon

---

README.md
play/android-publisher/src/main/kotlin/com/github/triplet/gradle/androidpublisher/PlayPublisher.kt
play/android-publisher/src/main/kotlin/com/github/triplet/gradle/androidpublisher/internal/AndroidPublisher.kt
play/android-publisher/src/main/kotlin/com/github/triplet/gradle/androidpublisher/internal/DefaultPlayPublisher.kt
play/android-publisher/src/testFixtures/kotlin/com/github/triplet/gradle/androidpublisher/FakePlayPublisher.kt
play/plugin/build.gradle.kts
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt
play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayApiService.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/PlayPublisherExtensionTest.kt
play/plugin/src/test/kotlin/com/github/triplet/gradle/play/PlayPublisherPluginIntegrationTest.kt

Usage of Service Account keys is [generally discouraged](https://cloud.google.com/iam/docs/best-practices-service-accounts#service-account-keys), with service account [impersonation](https://cloud.google.com/iam/docs/best-practices-service-accounts#choose-when-to-use) being a recommended alternative.
Allow [Application Default Credentials](https://cloud.google.com/docs/authentication/provide-credentials-adc) to be used, and support Service Account impersonation with it. This could be used as an alternative to the existing Service Account key authentication. Since it is an alternative method, it should not affect backwards compatibility.
One point of discussion is the default values used to build `ImpersonatedCredentials` in `AndroidPublisher.kt`. We think these are suitable defaults - …

Add Application Default Credentials & Service Account impersonation

---

play/android-publisher/src/main/kotlin/com/github/triplet/gradle/androidpublisher/internal/AndroidPublisher.kt

[This PR](https://github.com/Triple-T/gradle-play-publisher/pull/1148) added the capability to authenticate with application default credentials.
When the application default credentials are generated using [workload identity federation](https://cloud.google.com/iam/docs/workload-identity-federation) like in a Github action, the generated JSON doesn't contain `scopes`. As a result, the google-auth-library defaults to a scope of `https://www.googleapis.com/auth/cloud-platform`, which doesn't include the androidpublisher scope.
To support all forms of application default credentials (including Identity Pool Credentials), we should specify a scope. Some more info about this is also in https://github.com/googleapis/google-auth-library-java/issues/1274.

Add scope to default application credentials
